algo = input('digite algo: ')
print('os valor de classe do tipo', type(algo))
print('tem espacos', algo.isspace())
print('e alfanumerico', algo.isalnum())
print('e alfabetico', algo.isalpha())
print('os valor de classe do tipo', algo.isprintable())
print('estar e maiuscula', algo.isupper())
print('estar e minuscula', algo.islower())
