palavra = str('vasco da gama')
print(palavra)
print(palavra[2:2])
print(palavra[2:5])
print(palavra[2:])
print(palavra[:5])
print(len(palavra))
print(palavra.count('a'))
print(palavra.find('gama'))
print(palavra.find('android'))
print('vasco' in palavra)

print(palavra.upper())
print(palavra.lower())
print(palavra.capitalize())
print(palavra.title())
print(palavra.strip())
print(palavra.rstrip())
print(palavra.lstrip())
print(palavra.split())
print('-'.join(palavra))