palavra = 'Vasco da Gama'
print(palavra)
print(palavra[2])
print(palavra[2:5])
print(palavra[2:])
print(palavra[:5])
print(palavra[::2])
print(palavra[::-1])
print(len(palavra)) 
print(palavra.count('a'))
print(palavra.find('Gama'))
print(palavra.find('android'))
print('vasco' in palavra.lower())
print('Vasco' in palavra)
print('Vasco' not in palavra)
print(palavra.upper())
print(palavra.lower())
print(palavra.capitalize())
print(palavra.title())
print(palavra.strip())
print(palavra.rstrip())
print(palavra.lstrip())
print(palavra.split())
print('-'.join(palavra))
print(palavra.replace('Vasco', '@'))

